#! /bin/bash
#
# for Ubuntu AMI
#
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs npm git-core
git clone https://github.com/billroy/cw
cd cw
npm install
sudo node index -p 80
